name: Fabric OIDC Deploy

on:
  workflow_dispatch:       # Allows manual trigger from GitHub UI
  push:
    branches:
      - main               # Triggers on push to main branch

permissions:
  id-token: write          # Required for OIDC token exchange
  contents: read           # Required to access repo contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repo
        uses: actions/checkout@v4

      - name: 🔐 Login to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 📡 Call Microsoft Fabric API
        run: |
          echo "🔎 Getting access token for Fabric..."
          FABRIC_TOKEN=$(az account get-access-token \
            --resource=https://api.fabric.microsoft.com \
            --query accessToken -o tsv)

          echo "📥 Listing Fabric workspaces..."
          curl -X GET "https://api.fabric.microsoft.com/v1/workspaces" \
            -H "Authorization: Bearer $FABRIC_TOKEN" \
            -H "Content-Type: application/json"
